### ISSUE TITLE
Gas Properties - Main checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/gas-properties#1]
## Design
- [x] **Sim folder and design doc created** (Date: 02/12/2015) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed**
- [x] **Learning goals and standards identified** (Date: 09/28/2018)
- [x] **Design concept complete**  (Date: 10/28/2018)
- [x] **Wireframes complete** (Date: 10/18/2018) 
- [x] **Mockups complete** (Date: 11/15/2018) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [x] Results reported to team
  - [ ] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 6/11/19) 
  - [x] Performance acceptable, see #98
  - [x] Carefully review ?showPointerAreas, see #97
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder, see #99 
  - [x] Add an activity
 <s> - [ ] Sim primer draft</s> - #171
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive, see #172
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use), see #172
- [ ] **Post-publication items** 
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0), see #172
 <s> - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)</s> - #171
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: ?)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos (then `grunt generate-data` in perennial and check in)
- [x] **Development started** (Date: 7/16/18)
- [x] **Sim is "feature complete"** (Date: 5/15/19 @ 262 hours)
- [x] **Preliminary code review completed** see #109 (Date: 6/11/19) 
- [x] **Final code review completed** see #111 (Date: 7/9/19) 
- [x] **Pre-publication items** 
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits - see #28
- [x] **Published** (Date: 8/12/19) 
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
 
## QA
- [x] **Dev testing started** (Date: 6/11/19) 
- [x] **Dev testing completed** (Date: 6/18/19) 
- [x] **First RC published** (Date: 7/26/19)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 8/12/19)

**Comment by samreid** [comment]
I decided to reserve Issue #1 for the master checklist, will move other issues later on.

**Comment by pixelzoom** [comment]
The master checklist has changed since this issue was created, so I updated https://github.com/phetsims/gas-properties/issues/1#issue-201961727.

**Comment by pixelzoom** [comment]
Implementation and QA tasks are done.  Assigning to @arouinfar to complete the Design checklist.

**Comment by ariel-phet** [comment]
I think all remaining items here are for @arouinfar

**Comment by pixelzoom** [comment]
Since we published 1.1.0 today, and I don't see anything super important remaining in the checklist, I'm going to close this.
