### ISSUE TITLE
common-code issues that block 1.0 publication

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#35]
This issue tracks known common-code issues that must be resolved before 1.0 can be published.

- [x] https://github.com/phetsims/joist/issues/538, screen icons blend into navbar
- [x] https://github.com/phetsims/states-of-matter/issues/217, migrate BicyclePumpNode to scenery-phet

TimerNode:
- [x] https://github.com/phetsims/scenery-phet/issues/425, buggy layout of units in TimerNode
- [x] https://github.com/phetsims/scenery-phet/issues/429, change UI state when TimerNode reaches maxValue

GaugeNode:
- [x] https://github.com/phetsims/scenery-phet/issues/432, issues with GaugeNode
- [x] https://github.com/phetsims/scenery-phet/issues/440, Add a value readout to GaugeNode

HeaterCoolerNode:
- [x] https://github.com/phetsims/scenery-phet/issues/423, HeaterCoolerNode problems
- [x] https://github.com/phetsims/scenery-phet/issues/443, HeaterCoolerNode: default slider thumb looks disabled
- [x] https://github.com/phetsims/scenery-phet/issues/442, HeaterCoolerNode: add ability to hide slider

Scenery:
- [x] https://github.com/phetsims/scenery/issues/621, webgl test causes pause

**Comment by pixelzoom** [comment]
BicyclePumpNode has been integrated. There's still work to be done on it, but it's in a state where it's usable in Gas Properties.

webgl test problem mysteriously fixed itself.

All items checked, so closing.
